/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;
import Controlador.clsRegistroCliente;
import Modelo.daoRegistroCliente;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.util.HashSet;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class jDialog_vistaCliente extends javax.swing.JDialog {

    public void llenadoDeTablas() {
        DefaultTableModel tabla = new DefaultTableModel();
        tabla.addColumn("ID Cliente");
        tabla.addColumn("Nombre");
        tabla.addColumn("Apellido");
        tabla.addColumn("Dirección");
        tabla.addColumn("Teléfono");
        tabla.addColumn("Correo");
        tabla.addColumn("Estado");
        
        clsRegistroCliente moneda = new clsRegistroCliente();
        //VendedorDAO vendedorDAO = new VendedorDAO();

        List<clsRegistroCliente> listadoRegistroCliete = moneda.getListadoRegistroCliente();
        Tbl_registroCliente.setModel(tabla);
        String[] dato = new String[7];
        for (int i = 0; i < listadoRegistroCliete.size(); i++) {
            dato[0] = Integer.toString(listadoRegistroCliete.get(i).getid_cliente());
            dato[1] = listadoRegistroCliete .get(i).getnombre_cliente();
            dato[2] = listadoRegistroCliete .get(i).getapellido_cliente();
            dato[3] = listadoRegistroCliete .get(i).getdireccion_cliente();
            dato[4] = listadoRegistroCliete.get(i).gettelefono_cliente();
            dato[5] = listadoRegistroCliete .get(i).getcorreo_cliente();
            dato[6] = listadoRegistroCliete.get(i).getestado_cliente();
            tabla.addRow(dato);
        }       
    }
    /**
     * Creates new form jDialog_vistaCliente
     * @param parent
     * @param modal
     */
    public jDialog_vistaCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        llenadoDeTablas();
        
      DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
model.addElement("Seleccionar...");  
model.addElement("activo");
model.addElement("inactivo");
Cbo_estado.setModel(model);

// Establece el primer elemento como seleccionado (el elemento vacío)
Cbo_estado.setSelectedIndex(0);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pnl_panel7 = new javax.swing.JPanel();
        Btn_agregar = new javax.swing.JButton();
        Btn_eliminar = new javax.swing.JButton();
        Btn_modificar = new javax.swing.JButton();
        Btn_limpiar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        Txt_buscarId = new javax.swing.JTextField();
        Btn_buscarId = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Label_Usuario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Btn_actualizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Txt_nombre = new javax.swing.JTextField();
        Txt_dirección = new javax.swing.JTextField();
        Txt_apellido = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_registroCliente = new javax.swing.JTable();
        Txt_telefono = new javax.swing.JTextField();
        Txt_correo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Btn_ayuda = new javax.swing.JButton();
        Cbo_estado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Pnl_panel7.setBackground(new java.awt.Color(106, 135, 191));

        Btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        Btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_agregarActionPerformed(evt);
            }
        });

        Btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        Btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_eliminarActionPerformed(evt);
            }
        });

        Btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        Btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_modificarActionPerformed(evt);
            }
        });

        Btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar.png"))); // NOI18N
        Btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_limpiarActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Agregar");

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Eliminar");

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Editar");

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Limpiar");

        Btn_buscarId.setText("Buscar");
        Btn_buscarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_buscarIdActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID a buscar");

        javax.swing.GroupLayout Pnl_panel7Layout = new javax.swing.GroupLayout(Pnl_panel7);
        Pnl_panel7.setLayout(Pnl_panel7Layout);
        Pnl_panel7Layout.setHorizontalGroup(
            Pnl_panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_panel7Layout.createSequentialGroup()
                .addGroup(Pnl_panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_panel7Layout.createSequentialGroup()
                        .addGroup(Pnl_panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pnl_panel7Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Pnl_panel7Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel16))
                            .addGroup(Pnl_panel7Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(Btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Pnl_panel7Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(Pnl_panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Pnl_panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel42)
                                        .addComponent(Btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel43)
                                        .addComponent(Btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Pnl_panel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Pnl_panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn_buscarId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(Pnl_panel7Layout.createSequentialGroup()
                                .addGroup(Pnl_panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Pnl_panel7Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel9))
                                    .addGroup(Pnl_panel7Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(Txt_buscarId, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 18, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        Pnl_panel7Layout.setVerticalGroup(
            Pnl_panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_panel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(29, 29, 29)
                .addComponent(Btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel42)
                .addGap(18, 18, 18)
                .addComponent(Btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel41)
                .addGap(27, 27, 27)
                .addComponent(Btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel43)
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_buscarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_buscarId)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(106, 135, 191));

        Label_Usuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Label_Usuario.setText("REGISTRO CLIENTE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(Label_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(201, 217, 242));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(69, 84, 108));
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(69, 84, 108));
        jLabel4.setText("Apellido");

        Btn_actualizar.setText("Actualizar");
        Btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_actualizarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(69, 84, 108));
        jLabel5.setText("Dirección");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(69, 84, 108));
        jLabel6.setText("Teléfono");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(69, 84, 108));
        jLabel7.setText("Correo");

        Txt_dirección.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_direcciónActionPerformed(evt);
            }
        });

        Txt_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_apellidoActionPerformed(evt);
            }
        });

        Tbl_registroCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Tbl_registroCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Cliente", "Nombre", "Apellido", "Dirección", "Teléfono", "Correo", "Estado"
            }
        ));
        jScrollPane1.setViewportView(Tbl_registroCliente);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(69, 84, 108));
        jLabel8.setText("Estado");

        Btn_ayuda.setText("Ayuda");
        Btn_ayuda.setToolTipText("");
        Btn_ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ayudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Txt_dirección))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Txt_apellido))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Txt_correo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(Txt_telefono)
                            .addComponent(Cbo_estado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(380, 380, 380)
                        .addComponent(Btn_ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Txt_dirección, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Cbo_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_actualizar)
                    .addComponent(Btn_ayuda))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Pnl_panel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Pnl_panel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_agregarActionPerformed
        // TODO add your handling code here:
        clsRegistroCliente cliente = new clsRegistroCliente();
        cliente.setnombre_cliente(Txt_nombre.getText());
        cliente.setapellido_cliente(Txt_apellido.getText());
        cliente.setdireccion_cliente(Txt_dirección.getText());
        cliente.settelefono_cliente(Txt_telefono.getText());
        cliente.setcorreo_cliente(Txt_correo.getText());

        String estadoSeleccionado = (String) Cbo_estado.getSelectedItem();
            cliente.setestado_cliente(estadoSeleccionado.equalsIgnoreCase("activo") ? "activo" : "inactivo");
        daoRegistroCliente daoRegistroCliente = new daoRegistroCliente();
        int result = daoRegistroCliente.ingresarRegistroCliente(cliente);

        if (result > 0) {
            JOptionPane.showMessageDialog(null, "Registro Ingresado\n",
                "Información del Sistema", JOptionPane.INFORMATION_MESSAGE);
            llenadoDeTablas();
            limpiarTextos();
        } else {
            JOptionPane.showMessageDialog(null, "Error al ingresar registro\n",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Btn_agregarActionPerformed

    private void Btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_eliminarActionPerformed
        // TODO add your handling code here:
        int registrosBorrados=0;
        clsRegistroCliente cliente = new clsRegistroCliente();
        cliente.setid_cliente(Integer.parseInt(Txt_buscarId.getText()));
        registrosBorrados=cliente.setBorrarRegistroCliente(cliente);
        JOptionPane.showMessageDialog(null, "Registro Borrado\n",
            "Información del Sistema", JOptionPane.INFORMATION_MESSAGE);
        limpiarTextos();
    }//GEN-LAST:event_Btn_eliminarActionPerformed

    private void Btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_modificarActionPerformed
        // TODO add your handling code here:
        clsRegistroCliente cliente = new clsRegistroCliente();
        cliente.setid_cliente(Integer.parseInt(Txt_buscarId.getText()));
        cliente.setnombre_cliente(Txt_nombre.getText());
        cliente.setapellido_cliente(Txt_apellido.getText());
        cliente.setdireccion_cliente(Txt_dirección.getText());
        cliente.settelefono_cliente(Txt_telefono.getText());
        cliente.setcorreo_cliente(Txt_correo.getText());
        
        
        String estadoSeleccionado = (String) Cbo_estado.getSelectedItem();
        System.out.println("Estado seleccionado: " + estadoSeleccionado);
        cliente.setestado_cliente(estadoSeleccionado.equalsIgnoreCase("activo") ? "activo" : "inactivo");

        daoRegistroCliente dao = new daoRegistroCliente();
        int result = dao.actualizaRegistroCliente(cliente);

        if (result > 0) {
            JOptionPane.showMessageDialog(null, "Datos Modificados\n",
                "Información del Sistema", JOptionPane.INFORMATION_MESSAGE);
            llenadoDeTablas();
            limpiarTextos();
        } else {
            JOptionPane.showMessageDialog(null, "Error al modificar datos\n",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Btn_modificarActionPerformed

    private void Btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_limpiarActionPerformed
        // TODO add your handling code here:
        limpiarTextos();
        habilitarBotones();
    }//GEN-LAST:event_Btn_limpiarActionPerformed

    private void Btn_buscarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_buscarIdActionPerformed
        // TODO add your handling code here:

        clsRegistroCliente cliente = new clsRegistroCliente();
        cliente.setid_cliente(Integer.parseInt(Txt_buscarId.getText()));
        cliente = cliente.getBuscarInformacionRegistroClientePorId(cliente);

        if (cliente != null) {

            JOptionPane.showMessageDialog(this, "Cliente encontrado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            Txt_nombre.setText(cliente.getnombre_cliente());
            Txt_apellido.setText(cliente.getapellido_cliente());
            Txt_dirección.setText(cliente.getdireccion_cliente());
            Txt_telefono.setText(cliente.gettelefono_cliente());
            Txt_correo.setText(cliente.getcorreo_cliente());
            
             // Establecer el estado en el JComboBox
            String estado = cliente.getestado_cliente().equalsIgnoreCase("activo") ? "activo" : "inactivo";
            Cbo_estado.setSelectedItem(estado);

        } else {
            JOptionPane.showMessageDialog(null, "Error al encontrar Id del Cliente\n",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Btn_buscarIdActionPerformed

    private void Btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_actualizarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Tabla actualizada\n",
            "Información del Sistema", JOptionPane.INFORMATION_MESSAGE);
        llenadoDeTablas();
    }//GEN-LAST:event_Btn_actualizarActionPerformed

    private void Txt_direcciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_direcciónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_direcciónActionPerformed

    private void Txt_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_apellidoActionPerformed

    private void Btn_ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ayudaActionPerformed
        // TODO add your handling code here:
       try {
            if ((new File("src\\Ayudas\\ayuda archivo.chm")).exists()) {
                Process p = Runtime
                .getRuntime()
                .exec("rundll32 url.dll,FileProtocolHandler src\\Ayudas\\ayuda archivo.chm");
                p.waitFor();
            } else {
                System.out.println("La ayuda no fue encontrada");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        } 
        
        
    }//GEN-LAST:event_Btn_ayudaActionPerformed

        public void limpiarTextos()
    {

        Txt_nombre.setText("");
        Txt_apellido.setText("");
        Txt_dirección.setText("");
        Txt_telefono.setText("");
        Txt_correo.setText("");
        Cbo_estado.setSelectedIndex(0);
        Txt_buscarId.setText("");

    }
    public void habilitarBotones()
    {
        Btn_agregar.setEnabled(true);
        Btn_modificar.setEnabled(true);
        Btn_eliminar.setEnabled(true);
        Btn_ayuda.setEnabled(true);
        Btn_buscarId.setEnabled(true);
        Btn_limpiar.setEnabled(true);
        Btn_actualizar.setEnabled(true);

    }
    public void desHabilitarBotones()
    {
        Btn_agregar.setEnabled(true);
        Btn_modificar.setEnabled(true);
        Btn_eliminar.setEnabled(true);
        Btn_ayuda.setEnabled(true);
        Btn_buscarId.setEnabled(true);
        Btn_limpiar.setEnabled(true);
        Btn_actualizar.setEnabled(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jDialog_vistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jDialog_vistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jDialog_vistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jDialog_vistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            jDialog_vistaCliente dialog = new jDialog_vistaCliente(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_actualizar;
    private javax.swing.JButton Btn_agregar;
    private javax.swing.JButton Btn_ayuda;
    private javax.swing.JButton Btn_buscarId;
    private javax.swing.JButton Btn_eliminar;
    private javax.swing.JButton Btn_limpiar;
    private javax.swing.JButton Btn_modificar;
    private javax.swing.JComboBox<String> Cbo_estado;
    private javax.swing.JLabel Label_Usuario;
    private javax.swing.JPanel Pnl_panel7;
    private javax.swing.JTable Tbl_registroCliente;
    private javax.swing.JTextField Txt_apellido;
    private javax.swing.JTextField Txt_buscarId;
    private javax.swing.JTextField Txt_correo;
    private javax.swing.JTextField Txt_dirección;
    private javax.swing.JTextField Txt_nombre;
    private javax.swing.JTextField Txt_telefono;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
