
package Vista;

/**
 * @author Wendy Elizabeth Sacayón Fajardo 0901 - 21 - 125 
 */

import Controlador.ClsUsuario;
import Modelo.daoUsuario;
import java.awt.Frame;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.SimpleDateFormat;



public class jDialog_UsuarioVista extends javax.swing.JFrame {

    

    /**
     */
    
   ////////////////////////////////////////////////////////////////////////////
    
    public void llenadoDeTabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Contraseña");
        modelo.addColumn("Conf. ContrConfaseña");
        modelo.addColumn("Ultima Sesion");
        modelo.addColumn("Estatus");
        modelo.addColumn("Nombre Real");
        modelo.addColumn("Correo");
        modelo.addColumn("Telefono");
        modelo.addColumn("Direccion");
        modelo.addColumn("Tipo Usuario");
        
        ClsUsuario users = new ClsUsuario();
        
        List<ClsUsuario> listadoUsuarios =  users.getListadoUsuarios();
        TablaUsuario.setModel(modelo);
        String[] dato = new String[9];
        for (int i = 0; i < listadoUsuarios.size(); i++) {
            dato[0] = Integer.toString(listadoUsuarios.get(i).getId_usuario());
            dato[1] = listadoUsuarios .get(i).getNombre_usuario();
            dato[2] = listadoUsuarios .get(i).getContraseña_usuario();
            dato[3] = Date(listadoUsuarios .get(i).getUltima_sesion_usuario());
            dato[5] = listadoUsuarios .get(i).getStatus_usuario();
            dato[6] = listadoUsuarios .get(i).getNombre_real_usuario();
            dato[7] = listadoUsuarios .get(i).getCorreo_usuario();
            dato[8] = listadoUsuarios .get(i).getTelefono_usuario();
            dato[9] = listadoUsuarios .get(i).getDireccion_usuario();
            dato[10] = Integer.toString(listadoUsuarios.get(i).getId_tipo_usuario());
            modelo.addRow(dato);
        }
    }
  

       /* *  Creates new form jDialog_vistaCliente
            * @param parent
            * @param modal*/

public jDialog_UsuarioVista() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        llenadoDeTabla();
    }

    //*private void initComponents() {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}
    //public class VistaUsuario
    


  /*   public frmMantenimientoTablaUsuario() {
        initComponents();
        llenadoDeTablas();
    }*/
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Label_Usuario = new javax.swing.JLabel();
        Label_nombre = new javax.swing.JLabel();
        Label_contraseña = new javax.swing.JLabel();
        Label_ultimaSesion = new javax.swing.JLabel();
        Label_estatus = new javax.swing.JLabel();
        Label_nombreReal = new javax.swing.JLabel();
        Label_Correo = new javax.swing.JLabel();
        Label_telefono = new javax.swing.JLabel();
        Label_direccion = new javax.swing.JLabel();
        Label_tipoUsuario = new javax.swing.JLabel();
        Txt_Nombre = new javax.swing.JTextField();
        txt_Contraseña = new javax.swing.JTextField();
        Txt_UltimaSesion = new javax.swing.JTextField();
        Txt_Estatus = new javax.swing.JTextField();
        Txt_nomReal = new javax.swing.JTextField();
        Txt_Correo = new javax.swing.JTextField();
        Txt_Telefomo = new javax.swing.JTextField();
        Txt_Direccion = new javax.swing.JTextField();
        Txt_TipoUsuario = new javax.swing.JTextField();
        Btn_registrar = new javax.swing.JButton();
        Btn_modificar = new javax.swing.JButton();
        Btn_limpiar = new javax.swing.JButton();
        Btn_ayuda = new javax.swing.JButton();
        Btn_reportes = new javax.swing.JButton();
        Btn_buscar = new javax.swing.JButton();
        Btn_actualizar = new javax.swing.JButton();
        Btn_eliminar = new javax.swing.JButton();
        Label_idabuscar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaUsuario = new javax.swing.JTable();
        Txt_buscar = new javax.swing.JTextField();
        Label_actualizar = new javax.swing.JLabel();
        Label_reporte = new javax.swing.JLabel();
        Label_ayuda = new javax.swing.JLabel();
        Label_Limpiar = new javax.swing.JLabel();
        Label_eliminar = new javax.swing.JLabel();
        Label_modificar = new javax.swing.JLabel();
        Label_registra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(160, 21, 62));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        Label_Usuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Label_Usuario.setText("USUARIO ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Label_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Label_nombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_nombre.setForeground(new java.awt.Color(255, 255, 255));
        Label_nombre.setText("Nombre");

        Label_contraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_contraseña.setForeground(new java.awt.Color(255, 255, 255));
        Label_contraseña.setText("Contraseña");

        Label_ultimaSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_ultimaSesion.setForeground(new java.awt.Color(255, 255, 255));
        Label_ultimaSesion.setText("Ultima Sesion");

        Label_estatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_estatus.setForeground(new java.awt.Color(255, 255, 255));
        Label_estatus.setText("Estatus");

        Label_nombreReal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_nombreReal.setForeground(new java.awt.Color(255, 255, 255));
        Label_nombreReal.setText("Nombre Real");

        Label_Correo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_Correo.setForeground(new java.awt.Color(255, 255, 255));
        Label_Correo.setText("Correo");

        Label_telefono.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_telefono.setForeground(new java.awt.Color(255, 255, 255));
        Label_telefono.setText("Telefono");

        Label_direccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_direccion.setForeground(new java.awt.Color(255, 255, 255));
        Label_direccion.setText("Dirección ");

        Label_tipoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_tipoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        Label_tipoUsuario.setText("Tipo de Usuario");

        Txt_Nombre.setBackground(new java.awt.Color(0, 0, 0));
        Txt_Nombre.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Txt_Nombre.setText("jTextField1");

        txt_Contraseña.setBackground(new java.awt.Color(0, 0, 0));
        txt_Contraseña.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_Contraseña.setText("jTextField2");
        txt_Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ContraseñaActionPerformed(evt);
            }
        });

        Txt_UltimaSesion.setBackground(new java.awt.Color(0, 0, 0));
        Txt_UltimaSesion.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Txt_UltimaSesion.setText("jTextField4");

        Txt_Estatus.setBackground(new java.awt.Color(0, 0, 0));
        Txt_Estatus.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Txt_Estatus.setText("jTextField5");

        Txt_nomReal.setBackground(new java.awt.Color(0, 0, 0));
        Txt_nomReal.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Txt_nomReal.setText("jTextField6");

        Txt_Correo.setBackground(new java.awt.Color(0, 0, 0));
        Txt_Correo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Txt_Correo.setText("jTextField7");

        Txt_Telefomo.setBackground(new java.awt.Color(0, 0, 0));
        Txt_Telefomo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Txt_Telefomo.setText("jTextField8");

        Txt_Direccion.setBackground(new java.awt.Color(0, 0, 0));
        Txt_Direccion.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Txt_Direccion.setText("jTextField9");

        Txt_TipoUsuario.setBackground(new java.awt.Color(0, 0, 0));
        Txt_TipoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Txt_TipoUsuario.setText("jTextField10");

        Btn_registrar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Btn_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registrar.png"))); // NOI18N
        Btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_registrarActionPerformed(evt);
            }
        });

        Btn_modificar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        Btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_modificarActionPerformed(evt);
            }
        });

        Btn_limpiar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar.png"))); // NOI18N
        Btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_limpiarActionPerformed(evt);
            }
        });

        Btn_ayuda.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Btn_ayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ayuda.png"))); // NOI18N

        Btn_reportes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Btn_reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reportes.png"))); // NOI18N

        Btn_buscar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        Btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_buscarActionPerformed(evt);
            }
        });

        Btn_actualizar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        Btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_actualizarActionPerformed(evt);
            }
        });

        Btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        Btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_eliminarActionPerformed(evt);
            }
        });

        Label_idabuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_idabuscar.setForeground(new java.awt.Color(255, 255, 255));
        Label_idabuscar.setText("ID a buscar ");

        TablaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Contraseña", "Conf. Contraseña", "Ultima Sesion", "Estatus", "Nombre Real", "Correo", "Telefono", "Direccion", "Tipo Usuariol"
            }
        ));
        jScrollPane2.setViewportView(TablaUsuario);

        Label_actualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_actualizar.setForeground(new java.awt.Color(255, 255, 255));
        Label_actualizar.setText("Actualizar");

        Label_reporte.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_reporte.setForeground(new java.awt.Color(255, 255, 255));
        Label_reporte.setText("Reporte");

        Label_ayuda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_ayuda.setForeground(new java.awt.Color(255, 255, 255));
        Label_ayuda.setText(" Ayuda");

        Label_Limpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_Limpiar.setForeground(new java.awt.Color(255, 255, 255));
        Label_Limpiar.setText("Limpiar");

        Label_eliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        Label_eliminar.setText("Eliminar");

        Label_modificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_modificar.setForeground(new java.awt.Color(255, 255, 255));
        Label_modificar.setText("Modificar");

        Label_registra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_registra.setForeground(new java.awt.Color(255, 255, 255));
        Label_registra.setText("Registrar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Label_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Btn_registrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Label_registra)
                                .addGap(23, 23, 23)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_direccion)
                                    .addComponent(Label_telefono)
                                    .addComponent(Label_Correo)
                                    .addComponent(Label_nombreReal)
                                    .addComponent(Label_estatus)
                                    .addComponent(Label_ultimaSesion)
                                    .addComponent(Label_contraseña)
                                    .addComponent(Label_nombre)
                                    .addComponent(Label_tipoUsuario))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Txt_Direccion)
                                        .addComponent(Txt_Telefomo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Txt_Correo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Txt_nomReal, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Txt_Estatus, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Txt_UltimaSesion, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_Contraseña)
                                        .addComponent(Txt_TipoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                                    .addComponent(Txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Label_ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(Label_idabuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(Btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(20, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn_ayuda)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_modificar)
                                    .addComponent(Btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Btn_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Label_reporte))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(Label_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_actualizar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Btn_actualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(311, 311, 311))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_nombre)
                            .addComponent(Txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_contraseña)
                            .addComponent(txt_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_ultimaSesion)
                            .addComponent(Txt_UltimaSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_estatus)
                            .addComponent(Txt_Estatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_nombreReal)
                            .addComponent(Txt_nomReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Correo)
                            .addComponent(Txt_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_telefono)
                            .addComponent(Txt_Telefomo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_direccion)
                            .addComponent(Txt_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_tipoUsuario)
                            .addComponent(Txt_TipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(Btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Label_actualizar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Label_Limpiar)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(Label_modificar))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Label_registra)))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Btn_ayuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(Btn_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label_ayuda)
                                    .addComponent(Label_eliminar)
                                    .addComponent(Label_reporte))
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Btn_buscar)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Label_idabuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(33, 33, 33))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_limpiarActionPerformed
         limpiarTextos();
        habilitarBotones();
    }//GEN-LAST:event_Btn_limpiarActionPerformed

    public void limpiarTextos()
    {
        Txt_Nombre.setText("");
        txt_Contraseña.setText("");
        Txt_UltimaSesion.setText("");
        Txt_Estatus.setText("");
        Txt_nomReal.setText("");
        Txt_Correo.setText("");
        Txt_Telefomo.setText("");
        Txt_Direccion.setText("");
        Txt_TipoUsuario.setText("");

    }
    public void habilitarBotones()
    {
        Btn_modificar.setEnabled(true);
        Btn_eliminar.setEnabled(true);
        Btn_ayuda.setEnabled(true);
        Btn_buscar.setEnabled(true);
        Btn_limpiar.setEnabled(true);
        Btn_actualizar.setEnabled(true);

    }
    public void desHabilitarBotones()
    {
        Btn_modificar.setEnabled(true);
        Btn_eliminar.setEnabled(true);
        Btn_ayuda.setEnabled(true);
        Btn_buscar.setEnabled(true);
        Btn_limpiar.setEnabled(true);
        Btn_actualizar.setEnabled(true);

    }
    
    private void Btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_eliminarActionPerformed
        int registrosBorrados=0;
        ClsUsuario usuario = new ClsUsuario();
        usuario.setId_usuario(Integer.parseInt(Txt_buscar.getText()));
        registrosBorrados=usuario.setBorrarUsuarios(usuario);
        JOptionPane.showMessageDialog(null, "Registro Borrado\n", 
                    "Información del Sistema", JOptionPane.INFORMATION_MESSAGE);
        limpiarTextos();
    }//GEN-LAST:event_Btn_eliminarActionPerformed

    private void Btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_modificarActionPerformed
    ClsUsuario usuario = new ClsUsuario(); 
    


                
    }//GEN-LAST:event_Btn_modificarActionPerformed

    private void Btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_registrarActionPerformed
       ClsUsuario usuario = new ClsUsuario(); 
    usuario.setNombre_usuario(Txt_Nombre.getText());
    usuario.setContraseña_usuario(txt_Contraseña.getText());   
    usuario.setUltima_sesion_usuario(Txt_UltimaSesion.getText());
    usuario.setStatus_usuario(Txt_Estatus.getText());
    usuario.setNombre_real_usuario(Txt_nomReal.getText());
    usuario.setCorreo_usuario(Txt_Correo.getText());
    usuario.setTelefono_usuario(Txt_Telefomo.getText());
    usuario.setDireccion_usuario(Txt_Direccion.getText());
    usuario.setId_tipo_usuario(Integer.parseInt(Txt_TipoUsuario.getText()));
    
     daoUsuario daoUsuario = new daoUsuario();
    int result = daoUsuario.ingresaUsuario(usuario);

    if (result > 0) {
        JOptionPane.showMessageDialog(null, "Registro Ingresado\n", 
                "Información del Sistema", JOptionPane.INFORMATION_MESSAGE);        
        llenadoDeTabla();
        limpiarTextos();
    } else {
        JOptionPane.showMessageDialog(null, "Error al ingresar registro\n", 
                "Error", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_Btn_registrarActionPerformed

    private void Btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_buscarActionPerformed
        // TODO add your handling code here:
         ClsUsuario usuario = new ClsUsuario();      
        usuario.setId_usuario(Integer.parseInt(Txt_buscar.getText()));        
        usuario = usuario.getBuscarUsuarioPorID(usuario);
        
        if (usuario != null) {
            
            JOptionPane.showMessageDialog(this, "Usuario encontrado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE); 
        
            Txt_Nombre.setText(usuario.getNombre_usuario());
            txt_Contraseña.setText(usuario.getContraseña_usuario());            
            Txt_UltimaSesion.setText(usuario.getUltima_sesion_usuario());
            Txt_Estatus.setText(usuario.getStatus_usuario());
            Txt_nomReal.setText(usuario.getNombre_real_usuario());
            Txt_Correo.setText(usuario.getCorreo_usuario());
            Txt_Telefomo.setText(usuario.getTelefono_usuario());
            Txt_Direccion.setText(usuario.getDireccion_usuario());
            Txt_TipoUsuario.setText(usuario.getId_tipo_usuario());
            
        } else {
            JOptionPane.showMessageDialog(this, "Usuario no encontrado");
        } 
    }//GEN-LAST:event_Btn_buscarActionPerformed

    private void Btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_actualizarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Tabla actualizada\n", 
                    "Información del Sistema", JOptionPane.INFORMATION_MESSAGE);
        llenadoDeTabla();
    }//GEN-LAST:event_Btn_actualizarActionPerformed

    private void txt_ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ContraseñaActionPerformed

   
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jDialog_UsuarioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jDialog_UsuarioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jDialog_UsuarioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jDialog_UsuarioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jDialog_UsuarioVista().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_actualizar;
    private javax.swing.JButton Btn_ayuda;
    private javax.swing.JButton Btn_buscar;
    private javax.swing.JButton Btn_eliminar;
    private javax.swing.JButton Btn_limpiar;
    private javax.swing.JButton Btn_modificar;
    private javax.swing.JButton Btn_registrar;
    private javax.swing.JButton Btn_reportes;
    private javax.swing.JLabel Label_Correo;
    private javax.swing.JLabel Label_Limpiar;
    private javax.swing.JLabel Label_Usuario;
    private javax.swing.JLabel Label_actualizar;
    private javax.swing.JLabel Label_ayuda;
    private javax.swing.JLabel Label_contraseña;
    private javax.swing.JLabel Label_direccion;
    private javax.swing.JLabel Label_eliminar;
    private javax.swing.JLabel Label_estatus;
    private javax.swing.JLabel Label_idabuscar;
    private javax.swing.JLabel Label_modificar;
    private javax.swing.JLabel Label_nombre;
    private javax.swing.JLabel Label_nombreReal;
    private javax.swing.JLabel Label_registra;
    private javax.swing.JLabel Label_reporte;
    private javax.swing.JLabel Label_telefono;
    private javax.swing.JLabel Label_tipoUsuario;
    private javax.swing.JLabel Label_ultimaSesion;
    private javax.swing.JTable TablaUsuario;
    private javax.swing.JTextField Txt_Correo;
    private javax.swing.JTextField Txt_Direccion;
    private javax.swing.JTextField Txt_Estatus;
    private javax.swing.JTextField Txt_Nombre;
    private javax.swing.JTextField Txt_Telefomo;
    private javax.swing.JTextField Txt_TipoUsuario;
    private javax.swing.JTextField Txt_UltimaSesion;
    private javax.swing.JTextField Txt_buscar;
    private javax.swing.JTextField Txt_nomReal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txt_Contraseña;
    // End of variables declaration//GEN-END:variables
}
