/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Controlador.clsRenta;
//import Controlador.clsRegistroCliente;
import java.awt.Component;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.HashSet;
import java.util.Set;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author sofia
 */
public class jDialog_Renta extends javax.swing.JDialog {

     /* public void llenadoDeComboCliente() {
        clsRegistroCliente cliente = new clsRegistroCliente();
        List<clsRegistroCliente> listadoClientes = cliente.getListadoRegistroCliente();
        Cbo_cliente.setAlignmentX(Component.CENTER_ALIGNMENT);
        Cbo_cliente.addItem("Seleccionar...");
        for (int i = 0; i < listadoClientes.size(); i++) {
            clsRegistroCliente Cliente = listadoClientes.get(i);
            String item = Cliente.getid_cliente() + " - " + Cliente.getnombre_cliente();
            Cbo_cliente.addItem(item);
        } 
    }*/
      
        
      /*public void llenadoDeComboVideo() {
        clsVideo video = new clsVideo();
        List<clsVideo> listadoVideos = video.getListadoVideos();
        Cbo_video.setAlignmentX(Component.CENTER_ALIGNMENT);
        Cbo_video.addItem("Seleccionar...");
        for (int i = 0; i < listadoVideos.size(); i++) {
            clsVideo Banco = listadoVideos.get(i);
            String item = Video.getIdVideo() + " - " + Video.getNombreVideo();
            Cbo_video.addItem(item);
        }
    }*/
        
    public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Fecha Alquiler");
        modelo.addColumn("Fecha Devolución");
        modelo.addColumn("Estatus");
        modelo.addColumn("Nombre Video");
        
        clsRenta renta = new clsRenta();
        
        List<clsRenta> ListadoRenta = renta.getListadoRentas();
        Tbl_alquilerVideos.setModel(modelo);
        String[] dato = new String[6];
        for (int i = 0; i < ListadoRenta.size(); i++) {
            dato[0] = Integer.toString(ListadoRenta.get(i).getId_comprobante());
            dato[1] = Integer.toString(ListadoRenta.get(i).getId_cliente());
            dato[2] = ListadoRenta.get(i).getFecha_alquiler();
            dato[3] = ListadoRenta.get(i).getFecha_devolucion();
            dato[4] = ListadoRenta.get(i).getEstatus_alquiler();
            dato[5] = Integer.toString(ListadoRenta.get(i).getId_video());
            modelo.addRow(dato);
        }   
    }
   
    public jDialog_Renta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        llenadoDeTablas();
        //llenadoDeComboCliente();
     
        //llenadoDeComboVideo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tbl_alquilerVideos = new javax.swing.JTable();
        Cbo_cliente = new javax.swing.JComboBox<>();
        lbl_Cliente2 = new javax.swing.JLabel();
        pan_video = new javax.swing.JPanel();
        lbl_video = new javax.swing.JLabel();
        Cbo_idVideo = new javax.swing.JComboBox<>();
        lbl_PrecioRenta = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_FechaInicio = new javax.swing.JLabel();
        Txt_fechaInicioRenta = new javax.swing.JTextField();
        Txt_fechaDevolucionRenta = new javax.swing.JTextField();
        lbl_FechaFin = new javax.swing.JLabel();
        Btn_registrar = new javax.swing.JButton();
        Btn_eliminar = new javax.swing.JButton();
        Btn_modificar = new javax.swing.JButton();
        Btn_limpiar = new javax.swing.JButton();
        lbl_cantidad4 = new javax.swing.JLabel();
        Txt_buscado = new javax.swing.JTextField();
        Btn_buscar = new javax.swing.JButton();
        Btn_ayuda = new javax.swing.JButton();
        Btn_actualizar = new javax.swing.JButton();
        Rdb_rentado = new javax.swing.JRadioButton();
        Rdb_devuelto = new javax.swing.JRadioButton();
        Txt_idAlquiler = new javax.swing.JTextField();
        lbl_Cliente1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nombre.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("ALQUILER DE VIDEOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        Tbl_alquilerVideos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Tbl_alquilerVideos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Alquiler", "Cliente", "Alquiler", "Devolución", "Estatus", "Video"
            }
        ));
        jScrollPane3.setViewportView(Tbl_alquilerVideos);

        Cbo_cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        Cbo_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cbo_clienteActionPerformed(evt);
            }
        });

        lbl_Cliente2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Cliente2.setText("Cliente:");

        pan_video.setBackground(new java.awt.Color(51, 51, 51));
        pan_video.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_video.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_video.setForeground(new java.awt.Color(255, 255, 255));
        lbl_video.setText("Video a Rentar");

        Cbo_idVideo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Video1", "Video2", "Video3", "Video4" }));

        lbl_PrecioRenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_PrecioRenta.setForeground(new java.awt.Color(255, 255, 255));
        lbl_PrecioRenta.setText("Estatus Renta");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("PORTADA");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Periodo Préstamo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        lbl_FechaInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_FechaInicio.setForeground(new java.awt.Color(255, 255, 255));
        lbl_FechaInicio.setText("Fecha Renta:");

        Txt_fechaInicioRenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_fechaInicioRentaActionPerformed(evt);
            }
        });

        Txt_fechaDevolucionRenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_fechaDevolucionRentaActionPerformed(evt);
            }
        });

        lbl_FechaFin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_FechaFin.setForeground(new java.awt.Color(255, 255, 255));
        lbl_FechaFin.setText("Fecha Devolución:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_FechaFin)
                    .addComponent(lbl_FechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Txt_fechaInicioRenta, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(Txt_fechaDevolucionRenta))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_FechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_fechaInicioRenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_FechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_fechaDevolucionRenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Btn_registrar.setBackground(new java.awt.Color(0, 102, 255));
        Btn_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        Btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_registrarActionPerformed(evt);
            }
        });

        Btn_eliminar.setBackground(new java.awt.Color(0, 102, 255));
        Btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        Btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_eliminarActionPerformed(evt);
            }
        });

        Btn_modificar.setBackground(new java.awt.Color(0, 102, 255));
        Btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        Btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_modificarActionPerformed(evt);
            }
        });

        Btn_limpiar.setBackground(new java.awt.Color(0, 102, 255));
        Btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar.png"))); // NOI18N
        Btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_limpiarActionPerformed(evt);
            }
        });

        lbl_cantidad4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_cantidad4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cantidad4.setText(" Id a Buscar");

        Txt_buscado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_buscadoActionPerformed(evt);
            }
        });

        Btn_buscar.setText("Buscar");
        Btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_buscarActionPerformed(evt);
            }
        });

        Btn_ayuda.setText("Ayuda");

        Btn_actualizar.setText("Actualizar");
        Btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_actualizarActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rdb_rentado);
        Rdb_rentado.setForeground(new java.awt.Color(255, 255, 255));
        Rdb_rentado.setText("Rentado");

        buttonGroup1.add(Rdb_devuelto);
        Rdb_devuelto.setForeground(new java.awt.Color(255, 255, 255));
        Rdb_devuelto.setText("Devuelto");

        javax.swing.GroupLayout pan_videoLayout = new javax.swing.GroupLayout(pan_video);
        pan_video.setLayout(pan_videoLayout);
        pan_videoLayout.setHorizontalGroup(
            pan_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_videoLayout.createSequentialGroup()
                .addGroup(pan_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_videoLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pan_videoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pan_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cbo_idVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_video, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pan_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_PrecioRenta, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pan_videoLayout.createSequentialGroup()
                                .addComponent(Rdb_rentado)
                                .addGap(18, 18, 18)
                                .addComponent(Rdb_devuelto))))
                    .addGroup(pan_videoLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(Btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(Btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(Btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(Btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pan_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pan_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Btn_ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pan_videoLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(lbl_cantidad4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Txt_buscado, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42))
        );
        pan_videoLayout.setVerticalGroup(
            pan_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_videoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_videoLayout.createSequentialGroup()
                        .addComponent(lbl_video, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pan_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cbo_idVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rdb_rentado)
                            .addComponent(Rdb_devuelto))
                        .addGap(28, 28, 28)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_PrecioRenta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 36, Short.MAX_VALUE)
                .addGroup(pan_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(pan_videoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pan_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cantidad4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_buscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_actualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_ayuda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_Cliente1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Cliente1.setText("Id Alquiler:");

        jMenu1.setText("Moras");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Listado Moras");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lbl_Cliente1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Txt_idAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(lbl_Cliente2)
                        .addGap(18, 18, 18)
                        .addComponent(Cbo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pan_video, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Cliente1)
                    .addComponent(Txt_idAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Cliente2)
                    .addComponent(Cbo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pan_video, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_fechaInicioRentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_fechaInicioRentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_fechaInicioRentaActionPerformed

    private void Txt_fechaDevolucionRentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_fechaDevolucionRentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_fechaDevolucionRentaActionPerformed

    private void Btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_modificarActionPerformed
        // TODO add your handling code here:
        clsRenta renta = new clsRenta();
        renta.setId_cliente(Integer.parseInt(Cbo_cliente.getSelectedItem().toString()));
        renta.setFecha_alquiler(Txt_fechaInicioRenta.getText());
        renta.setFecha_devolucion(Txt_fechaDevolucionRenta.getText());
        //renta.setEstatus_alquiler(Cbo_estatusAlquiler.getSelectedItem().toString());
        renta.setId_video(Integer.parseInt(Cbo_idVideo.getSelectedItem().toString()));
        JOptionPane.showMessageDialog(null, "Registro Modificado\n", 
                    "Información del Sistema", JOptionPane.INFORMATION_MESSAGE);      
        
        llenadoDeTablas();
        //limpiarTextos();
    }//GEN-LAST:event_Btn_modificarActionPerformed

    private void Txt_buscadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_buscadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_buscadoActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void Cbo_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cbo_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cbo_clienteActionPerformed

    private void Btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_registrarActionPerformed
        // TODO add your handling code here:
        clsRenta renta = new clsRenta();
        
        //cliente clsCliente
        String selectedItem = Cbo_cliente.getSelectedItem().toString();
        int item = Integer.parseInt(selectedItem.split(" - ")[0]);
        renta.setId_cliente(item);
        //renta.setId_cliente(Integer.parseInt(Cbo_cliente.getSelectedItem().toString()));
        
        String fecha_alquiler = Txt_fechaInicioRenta.getText();
        String fecha_renta = Txt_fechaDevolucionRenta.getText();
        
        /*//estatus combo
        String estadoSeleccionado = (String) Cbo_estatusAlquiler.getSelectedItem();
        renta.setEstatus_alquiler(estadoSeleccionado.equalsIgnoreCase("Rentado") ? "Rentado" : "Devuelto");
        if (estadoSeleccionado != null) {
        if (estadoSeleccionado.equalsIgnoreCase("Rentado")) {
        renta.setEstatus_alquiler("Rentado");
        } else if (estadoSeleccionado.equalsIgnoreCase("Devuelto")) {
        renta.setEstatus_alquiler("Devuelto");
        } else {
        // Manejo de caso en el que el valor seleccionado no es válido
        System.out.println("Error: Estado seleccionado no válido.");
         }
        } else {
        // Manejo de caso en el que no se seleccionó ningún valor
        System.out.println("Error: No se seleccionó ningún estado.");
        }
        //String estatus_Alquiler= Cbo_estatusAlquiler.getSelectedItem().toString();
        */
       
        //nombre video clsVideo
        String selectedItem2 = Cbo_idVideo.getSelectedItem().toString();
        int item2 = Integer.parseInt(selectedItem2.split(" - ")[0]);
        renta.setId_video(item2);
        //String id_video = Cbo_idVideo.getSelectedItem().toString();
        
        String estatusAlquiler = Rdb_rentado.isSelected() ? "T" : (Rdb_devuelto.isSelected() ? "F" : "");

        if (!estatusAlquiler.isEmpty()) {
        renta.setEstatus_alquiler(estatusAlquiler);
        JOptionPane.showMessageDialog(null, "Registro Ingresado\n", 
                "Información del Sistema", JOptionPane.INFORMATION_MESSAGE);

          llenadoDeTablas();
          limpiarTextos();
        } else {
        JOptionPane.showMessageDialog(null, "Debe seleccionar un estatus.");
        }
 
        //llenadoDeTablas();
        //llenadoDeComboCliente();
        //BusquedaComp();
        //limpiarTextos(); 
    
    }//GEN-LAST:event_Btn_registrarActionPerformed

    private void Btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_eliminarActionPerformed
        // TODO add your handling code here:
        int registrosBorrados=0;
        clsRenta renta = new clsRenta();
        renta.setId_comprobante(Integer.parseInt(Txt_buscado.getText()));
        registrosBorrados=renta.setBorrarRenta(renta);
        JOptionPane.showMessageDialog(null, "Registro Borrado\n", 
                    "Información del Sistema", JOptionPane.INFORMATION_MESSAGE);
        int resultadoBitacora=0;
        
        llenadoDeTablas();
        //limpiarTextos();
    }//GEN-LAST:event_Btn_eliminarActionPerformed

    private void Btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_limpiarActionPerformed
        // TODO add your handling code here:
        limpiarTextos();
        habilitarBotones();
    }//GEN-LAST:event_Btn_limpiarActionPerformed

    private void Btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_buscarActionPerformed
        // TODO add your handling code here:
        clsRenta renta = new clsRenta();
        renta.setId_comprobante(Integer.parseInt(Txt_buscado.getText()));
        renta = renta.getBuscarInformacionRentaPorId(renta);
        System.out.println("Renta retornada:" + renta);
        //Txt_idAlquiler.setText(renta.getId_comprobante());
        Txt_fechaInicioRenta.setText(renta.getFecha_alquiler());
        Txt_fechaDevolucionRenta.setText(renta.getFecha_devolucion());

        int cliente = renta.getId_cliente();
        for (int i = 1; i < Cbo_cliente.getItemCount(); i++) {
            int item = Integer.parseInt(Cbo_cliente.getItemAt(i).toString());
            if (item == cliente) {
                Cbo_cliente.setSelectedIndex(i);
                break;
            }
        }

        int video = renta.getId_video();
        for (int i = 1; i < Cbo_idVideo.getItemCount(); i++) {
            int item = Integer.parseInt(Cbo_idVideo.getItemAt(i).toString());
            if (item == video) {
                Cbo_idVideo.setSelectedIndex(i);
                break;
            }
        }
        
        /*String estatus = renta.getEstatus_alquiler();
        for (int i = 1; i < Cbo_estatusAlquiler.getItemCount(); i++) {
            String item = Cbo_estatusAlquiler.getItemAt(i).toString();
            if (item.equals(estatus)) {
                Cbo_estatusAlquiler.setSelectedIndex(i);
                break;
            }
        }        */
    }//GEN-LAST:event_Btn_buscarActionPerformed

    private void Btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_actualizarActionPerformed
        // TODO add your handling code here:
        llenadoDeTablas();
    }//GEN-LAST:event_Btn_actualizarActionPerformed
    

        public void limpiarTextos()
    {
        Txt_idAlquiler.setText("");
        Cbo_cliente.setSelectedIndex(0);
        Cbo_idVideo.setSelectedIndex(0);
        Txt_fechaInicioRenta.setText("");
        Txt_fechaDevolucionRenta.setText("");
        Txt_buscado.setText("");
    }
    public void habilitarBotones()
    {
        Btn_registrar.setEnabled(true);
        Btn_modificar.setEnabled(true);
        Btn_eliminar.setEnabled(true);
    }
    public void desHabilitarBotones()
    {
        Btn_registrar.setEnabled(true);
        Btn_modificar.setEnabled(true);
        Btn_eliminar.setEnabled(true);
    }    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jDialog_Renta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jDialog_Renta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jDialog_Renta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jDialog_Renta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jDialog_Renta dialog = new jDialog_Renta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_actualizar;
    private javax.swing.JButton Btn_ayuda;
    private javax.swing.JButton Btn_buscar;
    private javax.swing.JButton Btn_eliminar;
    private javax.swing.JButton Btn_limpiar;
    private javax.swing.JButton Btn_modificar;
    private javax.swing.JButton Btn_registrar;
    private javax.swing.JComboBox<String> Cbo_cliente;
    private javax.swing.JComboBox<String> Cbo_idVideo;
    private javax.swing.JRadioButton Rdb_devuelto;
    private javax.swing.JRadioButton Rdb_rentado;
    private javax.swing.JTable Tbl_alquilerVideos;
    private javax.swing.JTextField Txt_buscado;
    private javax.swing.JTextField Txt_fechaDevolucionRenta;
    private javax.swing.JTextField Txt_fechaInicioRenta;
    private javax.swing.JTextField Txt_idAlquiler;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_Cliente1;
    private javax.swing.JLabel lbl_Cliente2;
    private javax.swing.JLabel lbl_FechaFin;
    private javax.swing.JLabel lbl_FechaInicio;
    private javax.swing.JLabel lbl_PrecioRenta;
    private javax.swing.JLabel lbl_cantidad4;
    private javax.swing.JLabel lbl_video;
    private javax.swing.JPanel pan_video;
    // End of variables declaration//GEN-END:variables
}
