/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;


import Controlador.ClsUsuario;
import Modelo.daoUsuario;
import Controlador.clsTipUsu;
import java.awt.Component;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class jDialog_vistaUsuario extends javax.swing.JDialog {
    
         
      public void llenadoDeComboTipoUsuario() {
        clsTipUsu usuario = new clsTipUsu();
        List<clsTipUsu> listadoUsuario = usuario.getListadoUsuarios();
        Cbo_idTipoUsuario.setAlignmentX(Component.CENTER_ALIGNMENT);
        Cbo_idTipoUsuario.addItem("Seleccionar...");
        for (int i = 0; i < listadoUsuario.size(); i++) {
            clsTipUsu Usuario = listadoUsuario.get(i);
            String item = Usuario.getId_tipo_usuario() + " - " + Usuario.getNombre_tipo_usuario();
            Cbo_idTipoUsuario.addItem(item);
        }
    }
    
        public void llenadoDeTabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID Usuario");
        modelo.addColumn("Nombre");
        modelo.addColumn("Contraseña");
        modelo.addColumn("Ultima Sesion");
        modelo.addColumn("Estatus");
        modelo.addColumn("Nombre Real");
        modelo.addColumn("Correo");
        modelo.addColumn("Telefono");
        modelo.addColumn("Direccion");
        modelo.addColumn("Tipo Usuario");
        
        ClsUsuario users = new ClsUsuario();
        
        List<ClsUsuario> listadoUsuarios =  users.getListadoUsuario();
        Tbl_usuario.setModel(modelo);
        String[] dato = new String[10];
        
        for (int i = 0; i < listadoUsuarios.size(); i++) {
            dato[0] = Integer.toString(listadoUsuarios.get(i).getid_usuario());
            dato[1] = listadoUsuarios .get(i).getnombre_usuario();
            dato[2] = listadoUsuarios .get(i).getcontraseña_usuario();
            dato[3] = listadoUsuarios .get(i).getultima_sesion_usuario();
            dato[4] = listadoUsuarios .get(i).getstatus_usuario();
            dato[5] = listadoUsuarios .get(i).getnombre_real_usuario();
            dato[6] = listadoUsuarios .get(i).getcorreo_usuario();
            dato[7] = listadoUsuarios .get(i).gettelefono_usuario();
            dato[8] = listadoUsuarios .get(i).getdireccion_usuario();
            dato[9] = Integer.toString(listadoUsuarios.get(i).getid_tipo_usuario());
            modelo.addRow(dato);
        }
    }

    /**
     * Creates new form jDialog_vistaUsuario
     */
    public jDialog_vistaUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        llenadoDeTabla();
        llenadoDeComboTipoUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Label_Usuario = new javax.swing.JLabel();
        Label_nombre = new javax.swing.JLabel();
        Label_contraseña = new javax.swing.JLabel();
        Label_ultimaSesion = new javax.swing.JLabel();
        Label_estatus = new javax.swing.JLabel();
        Label_nombreReal = new javax.swing.JLabel();
        Label_Correo = new javax.swing.JLabel();
        Label_telefono = new javax.swing.JLabel();
        Label_direccion = new javax.swing.JLabel();
        Label_tipoUsuario = new javax.swing.JLabel();
        Txt_nombre = new javax.swing.JTextField();
        Txt_contraseña = new javax.swing.JTextField();
        Txt_ultimaSesion = new javax.swing.JTextField();
        Txt_status = new javax.swing.JTextField();
        Txt_nomReal = new javax.swing.JTextField();
        Txt_correo = new javax.swing.JTextField();
        Txt_telefono = new javax.swing.JTextField();
        Txt_direccion = new javax.swing.JTextField();
        Btn_registrar = new javax.swing.JButton();
        Btn_modificar = new javax.swing.JButton();
        Btn_limpiar = new javax.swing.JButton();
        Btn_ayuda = new javax.swing.JButton();
        Btn_reportes = new javax.swing.JButton();
        Btn_buscar = new javax.swing.JButton();
        Btn_actualizar = new javax.swing.JButton();
        Btn_eliminar = new javax.swing.JButton();
        Label_idabuscar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tbl_usuario = new javax.swing.JTable();
        Txt_buscar = new javax.swing.JTextField();
        Cbo_idTipoUsuario = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(160, 21, 62));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        Label_Usuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Label_Usuario.setText("USUARIO ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Label_nombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_nombre.setForeground(new java.awt.Color(255, 255, 255));
        Label_nombre.setText("Nombre");

        Label_contraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_contraseña.setForeground(new java.awt.Color(255, 255, 255));
        Label_contraseña.setText("Contraseña");

        Label_ultimaSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_ultimaSesion.setForeground(new java.awt.Color(255, 255, 255));
        Label_ultimaSesion.setText("Ultima Sesion");

        Label_estatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_estatus.setForeground(new java.awt.Color(255, 255, 255));
        Label_estatus.setText("Estatus");

        Label_nombreReal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_nombreReal.setForeground(new java.awt.Color(255, 255, 255));
        Label_nombreReal.setText("Nombre Real");

        Label_Correo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_Correo.setForeground(new java.awt.Color(255, 255, 255));
        Label_Correo.setText("Correo");

        Label_telefono.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_telefono.setForeground(new java.awt.Color(255, 255, 255));
        Label_telefono.setText("Telefono");

        Label_direccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_direccion.setForeground(new java.awt.Color(255, 255, 255));
        Label_direccion.setText("Dirección ");

        Label_tipoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_tipoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        Label_tipoUsuario.setText("Tipo de Usuario");

        Txt_nombre.setBackground(new java.awt.Color(204, 204, 204));

        Txt_contraseña.setBackground(new java.awt.Color(204, 204, 204));
        Txt_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_contraseñaActionPerformed(evt);
            }
        });

        Txt_ultimaSesion.setBackground(new java.awt.Color(204, 204, 204));

        Txt_status.setBackground(new java.awt.Color(204, 204, 204));

        Txt_nomReal.setBackground(new java.awt.Color(204, 204, 204));

        Txt_correo.setBackground(new java.awt.Color(204, 204, 204));

        Txt_telefono.setBackground(new java.awt.Color(204, 204, 204));

        Txt_direccion.setBackground(new java.awt.Color(204, 204, 204));
        Txt_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_direccionActionPerformed(evt);
            }
        });

        Btn_registrar.setText("Registrar");
        Btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_registrarActionPerformed(evt);
            }
        });

        Btn_modificar.setText("Modificar");
        Btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_modificarActionPerformed(evt);
            }
        });

        Btn_limpiar.setText("Limpiar");
        Btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_limpiarActionPerformed(evt);
            }
        });

        Btn_ayuda.setText("Ayuda");

        Btn_reportes.setText("Reportes");

        Btn_buscar.setText("Buscar");
        Btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_buscarActionPerformed(evt);
            }
        });

        Btn_actualizar.setText("Actualizar ");
        Btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_actualizarActionPerformed(evt);
            }
        });

        Btn_eliminar.setText("Eliminar");
        Btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_eliminarActionPerformed(evt);
            }
        });

        Label_idabuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_idabuscar.setForeground(new java.awt.Color(255, 255, 255));
        Label_idabuscar.setText("ID a buscar ");

        Tbl_usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Usuario", "Nombre", "Contraseña", "Ultima Sesion", "Estatus", "Nombre Real", "Correo", "Telefono", "Direccion", "Tipo Usuario"
            }
        ));
        jScrollPane2.setViewportView(Tbl_usuario);

        Cbo_idTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cbo_idTipoUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Btn_registrar, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(Btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(361, 361, 361))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(355, 355, 355)
                                .addComponent(Label_idabuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(Btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_direccion)
                                    .addComponent(Label_telefono)
                                    .addComponent(Label_Correo)
                                    .addComponent(Label_nombreReal)
                                    .addComponent(Label_estatus)
                                    .addComponent(Label_ultimaSesion)
                                    .addComponent(Label_contraseña)
                                    .addComponent(Label_nombre)
                                    .addComponent(Label_tipoUsuario))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Txt_direccion, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Txt_telefono)
                                    .addComponent(Txt_correo)
                                    .addComponent(Txt_nomReal)
                                    .addComponent(Txt_status)
                                    .addComponent(Txt_ultimaSesion)
                                    .addComponent(Txt_contraseña, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Txt_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(Cbo_idTipoUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Btn_modificar)
                                    .addComponent(Btn_ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(Btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Btn_reportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_nombre)
                            .addComponent(Txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_contraseña)
                            .addComponent(Txt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_ultimaSesion)
                            .addComponent(Txt_ultimaSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_estatus)
                            .addComponent(Txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_nombreReal)
                            .addComponent(Txt_nomReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Correo)
                            .addComponent(Txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_telefono)
                            .addComponent(Txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_direccion)
                            .addComponent(Txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_tipoUsuario)
                            .addComponent(Cbo_idTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                            .addComponent(Btn_ayuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_reportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Label_idabuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(33, 33, 33)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_contraseñaActionPerformed

    private void Txt_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_direccionActionPerformed

    private void Btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_registrarActionPerformed
    ClsUsuario usuario = new ClsUsuario(); 
    usuario.setnombre_usuario(Txt_nombre.getText());
    usuario.setcontraseña_usuario(Txt_contraseña.getText());  
    usuario.setultima_sesion_usuario(Txt_ultimaSesion.getText());
    usuario.setstatus_usuario(Txt_status.getText());
    usuario.setnombre_real_usuario(Txt_nomReal.getText());
    usuario.setcorreo_usuario(Txt_correo.getText());
    usuario.settelefono_usuario(Txt_telefono.getText());
    usuario.setdireccion_usuario(Txt_direccion.getText());


    String selectedItem2 = Cbo_idTipoUsuario.getSelectedItem().toString();
        int item2 = Integer.parseInt(selectedItem2.split(" - ")[0]);
        usuario.setid_tipo_usuario(item2);
        
    daoUsuario daoUsuario = new daoUsuario();
    int result = daoUsuario.ingresarUsuario(usuario);

    if (result > 0) {
        JOptionPane.showMessageDialog(null, "Registro Ingresado\n", 
                "Información del Sistema", JOptionPane.INFORMATION_MESSAGE);        
        llenadoDeTabla();
        limpiarTextos();
    } else {
        JOptionPane.showMessageDialog(null, "Error al ingresar registro\n", 
                "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_Btn_registrarActionPerformed

    private void Btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_modificarActionPerformed

       ClsUsuario usuario = new ClsUsuario(); 
      
        try { 
    usuario.setid_usuario(Integer.parseInt(Txt_buscar.getText()));
    usuario.setnombre_usuario(Txt_nombre.getText());
    usuario.setcontraseña_usuario(Txt_contraseña.getText());  
    usuario.setultima_sesion_usuario(Txt_ultimaSesion.getText());
    usuario.setstatus_usuario(Txt_status.getText());
    usuario.setnombre_real_usuario(Txt_nomReal.getText());
    usuario.setcorreo_usuario(Txt_correo.getText());
    usuario.settelefono_usuario(Txt_telefono.getText());
    usuario.setdireccion_usuario(Txt_direccion.getText());
    // Extraer y convertir el ID del usuario 
        String UsuarioSeleccionado = Cbo_idTipoUsuario.getSelectedItem().toString();
        int id_tipo_usuario = Integer.parseInt(UsuarioSeleccionado.split(" - ")[0].trim());
        usuario.setid_tipo_usuario(id_tipo_usuario);
        
    daoUsuario daoUsuario = new daoUsuario();
    int result = daoUsuario.actualizaUsuario(usuario);

         if (result > 0) {
        JOptionPane.showMessageDialog(null, "Datos Modificados\n", 
            "Información del Sistema", JOptionPane.INFORMATION_MESSAGE); 
        llenadoDeTabla();
        limpiarTextos();
        } else {
        JOptionPane.showMessageDialog(null, "Error al modificar datos\n", 
            "Error", JOptionPane.ERROR_MESSAGE);
        }
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Error al convertir el ID a número: " + e.getMessage(), 
        "Error", JOptionPane.ERROR_MESSAGE);
        }
   
    }//GEN-LAST:event_Btn_modificarActionPerformed

    private void Btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_limpiarActionPerformed
        limpiarTextos();
           
        habilitarBotones();
    }//GEN-LAST:event_Btn_limpiarActionPerformed
public void limpiarTextos()
    {
  
        Txt_nombre.setText("");
        Txt_contraseña.setText("");
        Txt_ultimaSesion.setText("");
        Txt_status.setText("");
        Txt_nomReal.setText("");
        Txt_correo.setText("");
        Txt_telefono.setText("");
        Txt_direccion.setText("");
        Txt_buscar.setText("");
        Cbo_idTipoUsuario.setSelectedIndex(0);

    }
    public void habilitarBotones()
    {
        Btn_registrar.setEnabled(true);
        Btn_modificar.setEnabled(true);
        Btn_eliminar.setEnabled(true);
        Btn_ayuda.setEnabled(true);
        Btn_buscar.setEnabled(true);
        Btn_limpiar.setEnabled(true);
        Btn_actualizar.setEnabled(true);

    }
    public void desHabilitarBotones()
    {
        Btn_registrar.setEnabled(true);
        Btn_modificar.setEnabled(true);
        Btn_eliminar.setEnabled(true);
        Btn_ayuda.setEnabled(true);
        Btn_buscar.setEnabled(true);
        Btn_limpiar.setEnabled(true);
        Btn_actualizar.setEnabled(true);
    }
    
    private void Btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_buscarActionPerformed
        // TODO add your handling code here:
        ClsUsuario usuario = new ClsUsuario();
    String buscado = Txt_buscar.getText().trim();
        
                if (buscado.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El campo de búsqueda no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }

        try {
        usuario.setid_usuario(Integer.parseInt(buscado));
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido en el campo de búsqueda.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }
        usuario = usuario.getBuscarInformacionUsuarioPorId(usuario);

        if (usuario != null) {

            JOptionPane.showMessageDialog(this, "Usuario encontrado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);


            Txt_nombre.setText(usuario.getnombre_usuario());
            Txt_contraseña.setText(usuario.getcontraseña_usuario());
            Txt_ultimaSesion.setText(usuario.getultima_sesion_usuario());
            Txt_status.setText(usuario.getstatus_usuario());
            Txt_nomReal.setText(usuario.getnombre_real_usuario());
            Txt_correo.setText(usuario.getcorreo_usuario());
            Txt_telefono.setText(usuario.gettelefono_usuario());
            Txt_direccion.setText(usuario.getdireccion_usuario());

           
            // Seleccionar video en Cbo_idVideo
        int tipoUsuario = usuario.getid_tipo_usuario();
        boolean tipoUsuarioncontrado = false;
        for (int i = 0; i < Cbo_idTipoUsuario.getItemCount(); i++) {
        String item = Cbo_idTipoUsuario.getItemAt(i).toString().trim();
        try {
            int itemIdV = Integer.parseInt(item.split(" - ")[0]); // Ajusta según el formato de los ítems
            if (itemIdV == tipoUsuario) {
                Cbo_idTipoUsuario.setSelectedIndex(i);
                tipoUsuarioncontrado = true;
                break;
            }
        } catch (NumberFormatException e) {
            // Ignorar ítems que no se pueden convertir a entero
        }
        }
        if (!tipoUsuarioncontrado) {
        JOptionPane.showMessageDialog(this, "Tipo Usuario no encontrado en la lista", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

        } else {
            JOptionPane.showMessageDialog(this, "Usuario no encontrado");
        }
    }//GEN-LAST:event_Btn_buscarActionPerformed

    private void Btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_actualizarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Tabla actualizada\n",
            "Información del Sistema", JOptionPane.INFORMATION_MESSAGE);
        llenadoDeTabla();
    }//GEN-LAST:event_Btn_actualizarActionPerformed

    private void Btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_eliminarActionPerformed
        int registrosBorrados=0;
        ClsUsuario usuario = new ClsUsuario();
        usuario.setid_usuario(Integer.parseInt(Txt_buscar.getText()));
        registrosBorrados=usuario.setBorrarUsuario(usuario);
        JOptionPane.showMessageDialog(null, "Registro Borrado\n", 
                    "Información del Sistema", JOptionPane.INFORMATION_MESSAGE);
        limpiarTextos();
    }//GEN-LAST:event_Btn_eliminarActionPerformed

    private void Cbo_idTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cbo_idTipoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cbo_idTipoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jDialog_vistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jDialog_vistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jDialog_vistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jDialog_vistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jDialog_vistaUsuario dialog = new jDialog_vistaUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_actualizar;
    private javax.swing.JButton Btn_ayuda;
    private javax.swing.JButton Btn_buscar;
    private javax.swing.JButton Btn_eliminar;
    private javax.swing.JButton Btn_limpiar;
    private javax.swing.JButton Btn_modificar;
    private javax.swing.JButton Btn_registrar;
    private javax.swing.JButton Btn_reportes;
    private javax.swing.JComboBox<String> Cbo_idTipoUsuario;
    private javax.swing.JLabel Label_Correo;
    private javax.swing.JLabel Label_Usuario;
    private javax.swing.JLabel Label_contraseña;
    private javax.swing.JLabel Label_direccion;
    private javax.swing.JLabel Label_estatus;
    private javax.swing.JLabel Label_idabuscar;
    private javax.swing.JLabel Label_nombre;
    private javax.swing.JLabel Label_nombreReal;
    private javax.swing.JLabel Label_telefono;
    private javax.swing.JLabel Label_tipoUsuario;
    private javax.swing.JLabel Label_ultimaSesion;
    private javax.swing.JTable Tbl_usuario;
    private javax.swing.JTextField Txt_buscar;
    private javax.swing.JTextField Txt_contraseña;
    private javax.swing.JTextField Txt_correo;
    private javax.swing.JTextField Txt_direccion;
    private javax.swing.JTextField Txt_nomReal;
    private javax.swing.JTextField Txt_nombre;
    private javax.swing.JTextField Txt_status;
    private javax.swing.JTextField Txt_telefono;
    private javax.swing.JTextField Txt_ultimaSesion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
