/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Controlador.clsRenta;
import Controlador.clsRegistroCliente; //importamos la clase de Clientes
import Controlador.clsVideo; //importamos la clase de Videos
import Modelo.daoRegistroCliente;
import Modelo.daoRenta;
import java.awt.Component;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.HashSet;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;  // Para formatear fechas
import java.sql.Date;    
import java.text.ParseException;
import javax.swing.JTextField;

/**
 *
 * @author DELL
 */
public class jDialog_Renta extends javax.swing.JDialog {
     
     public void llenadoDeComboCliente() {
        clsRegistroCliente cliente = new clsRegistroCliente();
        List<clsRegistroCliente> listadoClientes = cliente.getListadoRegistroCliente();
        Cbo_cliente.setAlignmentX(Component.CENTER_ALIGNMENT);
        Cbo_cliente.addItem("Seleccionar...");
        for (int i = 0; i < listadoClientes.size(); i++) {
            clsRegistroCliente Cliente = listadoClientes.get(i);
            String item = Cliente.getid_cliente() + " - " + Cliente.getnombre_cliente();
            Cbo_cliente.addItem(item);
        } 
    }
      
        
      public void llenadoDeComboVideo() {
        clsVideo video = new clsVideo();
        List<clsVideo> listadoVideos = video.getListadoRegistroVideo();
        Cbo_idVideo.setAlignmentX(Component.CENTER_ALIGNMENT);
        Cbo_idVideo.addItem("Seleccionar...");
        for (int i = 0; i < listadoVideos.size(); i++) {
            clsVideo Video = listadoVideos.get(i);
            String item = Video.getId_video() + " - " + Video.getTitulo_video();
            Cbo_idVideo.addItem(item);
        }
    }
      
      SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
    public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Fecha Alquiler");
        modelo.addColumn("Fecha Devolución");
        modelo.addColumn("Estatus");
        modelo.addColumn("Nombre Video");
        
        clsRenta renta = new clsRenta();
        
        List<clsRenta> ListadoRenta = renta.getListadoRentas();
        Tbl_alquilerVideos.setModel(modelo);
        String[] dato = new String[6];
        for (int i = 0; i < ListadoRenta.size(); i++) {
            dato[0] = Integer.toString(ListadoRenta.get(i).getId_comprobante());
            dato[1] = Integer.toString(ListadoRenta.get(i).getId_cliente());
            // Convierte las fechas a String usando el formato deseado
            dato[2] = ListadoRenta.get(i).getFecha_alquiler() != null ? sdf.format(ListadoRenta.get(i).getFecha_alquiler()) : "";
            dato[3] = ListadoRenta.get(i).getFecha_devolucion() != null ? sdf.format(ListadoRenta.get(i).getFecha_devolucion()) : "";
            // Obtener el estado seleccionado del JComboBox
            /*String estadoSeleccionado = (String) Cbo_estatusAlquiler.getSelectedItem();
            dato[4] = estadoSeleccionado.equalsIgnoreCase("Rentado") ? "Rentado" : "Devuelto";*/
            dato[4] = ListadoRenta.get(i).getEstatus_alquiler();
            dato[5] = Integer.toString(ListadoRenta.get(i).getId_video());
            modelo.addRow(dato);
        }   
    }
   
    public jDialog_Renta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        llenadoDeTablas();
        llenadoDeComboCliente();
        llenadoDeComboVideo();
        //llenadoDeComboVideo
        this.setLocationRelativeTo(null);
        
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("Rentado");
        model.addElement("Devuelto");
        Cbo_estatusAlquiler.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pan_video = new javax.swing.JPanel();
        lbl_video = new javax.swing.JLabel();
        Cbo_idVideo = new javax.swing.JComboBox<>();
        lbl_PrecioRenta = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_FechaInicio = new javax.swing.JLabel();
        lbl_FechaFin = new javax.swing.JLabel();
        Txt_fechaInicioRenta = new com.toedter.calendar.JDateChooser();
        Txt_fechaDevolucionRenta = new com.toedter.calendar.JDateChooser();
        Btn_ayuda = new javax.swing.JButton();
        Btn_actualizar = new javax.swing.JButton();
        lbl_Cliente1 = new javax.swing.JLabel();
        lbl_Cliente2 = new javax.swing.JLabel();
        Cbo_cliente = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tbl_alquilerVideos = new javax.swing.JTable();
        Cbo_estatusAlquiler = new javax.swing.JComboBox<>();
        Txt_idAlquiler = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Btn_registrar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        Btn_eliminar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        Btn_modificar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        Btn_limpiar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        Txt_buscado = new javax.swing.JTextField();
        lbl_cantidad4 = new javax.swing.JLabel();
        Btn_buscar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Agregar");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Eliminar");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Editar");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(106, 135, 191));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ALQUILER DE VIDEOS");

        jLabel4.setBackground(new java.awt.Color(106, 135, 191));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/t39.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(596, 596, 596))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)))
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pan_video.setBackground(new java.awt.Color(201, 217, 242));
        pan_video.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_video.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_video.setForeground(new java.awt.Color(69, 84, 108));
        lbl_video.setText("Video a Rentar");

        lbl_PrecioRenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_PrecioRenta.setForeground(new java.awt.Color(69, 84, 108));
        lbl_PrecioRenta.setText("Estatus Renta");

        jPanel2.setBackground(new java.awt.Color(106, 135, 191));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Periodo Préstamo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        lbl_FechaInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_FechaInicio.setForeground(new java.awt.Color(255, 255, 255));
        lbl_FechaInicio.setText("Fecha Renta:");

        lbl_FechaFin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_FechaFin.setForeground(new java.awt.Color(255, 255, 255));
        lbl_FechaFin.setText("Fecha Devolución:");

        Txt_fechaInicioRenta.setDateFormatString("yyyy-MM-dd");

        Txt_fechaDevolucionRenta.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lbl_FechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Txt_fechaInicioRenta, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(lbl_FechaFin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Txt_fechaDevolucionRenta, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Txt_fechaDevolucionRenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_fechaInicioRenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_FechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_FechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        Btn_ayuda.setText("Ayuda");

        Btn_actualizar.setText("Actualizar");
        Btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_actualizarActionPerformed(evt);
            }
        });

        lbl_Cliente1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_Cliente1.setForeground(new java.awt.Color(69, 84, 108));
        lbl_Cliente1.setText("Id Alquiler:");

        lbl_Cliente2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_Cliente2.setForeground(new java.awt.Color(69, 84, 108));
        lbl_Cliente2.setText("Cliente:");

        Cbo_cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        Cbo_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cbo_clienteActionPerformed(evt);
            }
        });

        Tbl_alquilerVideos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Tbl_alquilerVideos.setForeground(new java.awt.Color(153, 153, 153));
        Tbl_alquilerVideos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Alquiler", "Cliente", "Alquiler", "Devolución", "Estatus", "Video"
            }
        ));
        jScrollPane3.setViewportView(Tbl_alquilerVideos);

        Cbo_estatusAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cbo_estatusAlquilerActionPerformed(evt);
            }
        });

        Txt_idAlquiler.setEditable(false);
        Txt_idAlquiler.setBackground(new java.awt.Color(102, 102, 102));
        Txt_idAlquiler.setForeground(new java.awt.Color(255, 255, 255));
        Txt_idAlquiler.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Txt_idAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_idAlquilerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_videoLayout = new javax.swing.GroupLayout(pan_video);
        pan_video.setLayout(pan_videoLayout);
        pan_videoLayout.setHorizontalGroup(
            pan_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_videoLayout.createSequentialGroup()
                .addGroup(pan_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_videoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pan_videoLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(pan_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pan_videoLayout.createSequentialGroup()
                                .addGroup(pan_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_Cliente1)
                                    .addComponent(lbl_video, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(pan_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Txt_idAlquiler)
                                    .addComponent(Cbo_idVideo, 0, 199, Short.MAX_VALUE))
                                .addGap(51, 51, 51)
                                .addGroup(pan_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_Cliente2)
                                    .addComponent(lbl_PrecioRenta))
                                .addGap(23, 23, 23)
                                .addGroup(pan_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Cbo_cliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Cbo_estatusAlquiler, 0, 211, Short.MAX_VALUE)))
                            .addGroup(pan_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pan_videoLayout.createSequentialGroup()
                                    .addComponent(Btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(406, 406, 406)
                                    .addComponent(Btn_ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(74, 74, 74))
        );
        pan_videoLayout.setVerticalGroup(
            pan_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_videoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pan_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Cliente1)
                    .addComponent(Txt_idAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Cliente2)
                    .addComponent(Cbo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pan_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_video, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cbo_idVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_PrecioRenta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cbo_estatusAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pan_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_actualizar)
                    .addComponent(Btn_ayuda))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(105, 135, 189));

        Btn_registrar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_registrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\Analisis-de-sistemas-II-grupo-3-LOGING-Usuario9959-21-5909\\Analisis-de-sistemas-II-grupo-3-LOGING-Usuario9959-21-5909\\RentaVideo\\src\\Imagenes\\guardar.png")); // NOI18N
        Btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_registrarActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("  Agregar");

        Btn_eliminar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        Btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_eliminarActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("   Eliminar ");

        Btn_modificar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        Btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_modificarActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("    Editar    ");

        Btn_limpiar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar.png"))); // NOI18N
        Btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_limpiarActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Limpiar");

        Txt_buscado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_buscadoActionPerformed(evt);
            }
        });

        lbl_cantidad4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_cantidad4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cantidad4.setText(" Id a Buscar");

        Btn_buscar.setText("Buscar");
        Btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_buscado, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_cantidad4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel19))
                            .addComponent(jLabel17)
                            .addComponent(jLabel15)))
                    .addComponent(Btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(26, 26, 26)
                .addComponent(Btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(30, 30, 30)
                .addComponent(Btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(29, 29, 29)
                .addComponent(Btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(47, 47, 47)
                .addComponent(lbl_cantidad4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_buscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_buscar)
                .addGap(28, 28, 28))
        );

        jMenu1.setText("Moras");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Listado Moras");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pan_video, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pan_video, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_modificarActionPerformed
// TODO add your handling code here:
        clsRenta renta = new clsRenta();

        try {
        // Extraer y convertir el ID del cliente
        String clienteSeleccionado = Cbo_cliente.getSelectedItem().toString();
        int idCliente = Integer.parseInt(clienteSeleccionado.split(" - ")[0].trim());
        renta.setId_cliente(idCliente);

        // Extraer y convertir el ID del video
        String videoSeleccionado = Cbo_idVideo.getSelectedItem().toString();
        int idVideo = Integer.parseInt(videoSeleccionado.split(" - ")[0].trim());
        renta.setId_video(idVideo);

        String fechaInicio = ((JTextField) Txt_fechaInicioRenta.getDateEditor().getUiComponent()).getText();
        String fechaFin = ((JTextField) Txt_fechaDevolucionRenta.getDateEditor().getUiComponent()).getText();

        if (!fechaInicio.isEmpty()) {
        try {
        renta.setFecha_alquiler(new java.sql.Date(new SimpleDateFormat("yyyy-MM-dd").parse(fechaInicio).getTime()));
        } catch (ParseException e) {
        JOptionPane.showMessageDialog(null, "Error al parsear la fecha de inicio: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }
        } else {
        renta.setFecha_alquiler(null);
        }

        if (!fechaFin.isEmpty()) {
        try {
        renta.setFecha_devolucion(new java.sql.Date(new SimpleDateFormat("yyyy-MM-dd").parse(fechaFin).getTime()));
        } catch (ParseException e) {
        JOptionPane.showMessageDialog(null, "Error al parsear la fecha de fin: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }
        } else {
        renta.setFecha_devolucion(null);
        }

        // Estatus renta
        String estadoSeleccionado = (String) Cbo_estatusAlquiler.getSelectedItem();
        System.out.println("Estado seleccionado:" + estadoSeleccionado);
        renta.setEstatus_alquiler(estadoSeleccionado.equalsIgnoreCase("Rentado") ? "Rentado" : "Devuelto");
       
        // Crear el DAO y actualizar la renta
        daoRenta dao = new daoRenta();
        int result = dao.actualizaRenta(renta);

        if (result > 0) {
        JOptionPane.showMessageDialog(null, "Datos Modificados\n", 
            "Información del Sistema", JOptionPane.INFORMATION_MESSAGE); 
        llenadoDeTablas();
        llenadoDeComboCliente();
        llenadoDeComboVideo();
        limpiarTextos();
        } else {
        JOptionPane.showMessageDialog(null, "Error al modificar datos\n", 
            "Error", JOptionPane.ERROR_MESSAGE);
        }
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Error al convertir el ID a número: " + e.getMessage(), 
        "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_Btn_modificarActionPerformed

    private void Txt_buscadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_buscadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_buscadoActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void Cbo_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cbo_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cbo_clienteActionPerformed

    private void Btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_registrarActionPerformed
        // TODO add your handling code here:
        clsRenta renta = new clsRenta();

        // cliente clsCliente
        String selectedItem = Cbo_cliente.getSelectedItem().toString();
        int item = Integer.parseInt(selectedItem.split(" - ")[0]);
        renta.setId_cliente(item);

        // Establecer las fechas usando JDateChooser
        String fechaInicio = ((JTextField)Txt_fechaInicioRenta.getDateEditor().getUiComponent()).getText();
        String fechaFin = ((JTextField)Txt_fechaDevolucionRenta.getDateEditor().getUiComponent()).getText();

        // Puedes considerar agregar un try-catch para asegurar que las fechas son válidas.
        try {
        renta.setFecha_alquiler(java.sql.Date.valueOf(fechaInicio));
        renta.setFecha_devolucion(java.sql.Date.valueOf(fechaFin));
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Formato de fecha incorrecto: " + e.getMessage(), 
        "Error", JOptionPane.ERROR_MESSAGE);
        return; // Salir si hay un error en el formato de fecha
        }

        // estado de la renta
        String estadoSeleccionado = (String) Cbo_estatusAlquiler.getSelectedItem();
        renta.setEstatus_alquiler(estadoSeleccionado.equalsIgnoreCase("Rentado") ? "Rentado" : "Devuelto");

        String selectedItem2 = Cbo_idVideo.getSelectedItem().toString();
        int item2 = Integer.parseInt(selectedItem2.split(" - ")[0]);
        renta.setId_video(item2);

        daoRenta daoRentas = new daoRenta();
        int result = daoRentas.ingresaRenta(renta);

        if (result > 0) {
        JOptionPane.showMessageDialog(null, "Registro Ingresado\n", 
            "Información del Sistema", JOptionPane.INFORMATION_MESSAGE);        
        llenadoDeTablas();
        limpiarTextos();
        } else {
        JOptionPane.showMessageDialog(null, "Error al ingresar registro\n", 
            "Error", JOptionPane.ERROR_MESSAGE);
        }

        llenadoDeTablas();
        llenadoDeComboCliente();
        llenadoDeComboVideo();
    
    }//GEN-LAST:event_Btn_registrarActionPerformed

    private void Btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_eliminarActionPerformed
        // TODO add your handling code here:
        int registrosBorrados=0;
        clsRenta renta = new clsRenta();
        renta.setId_comprobante(Integer.parseInt(Txt_buscado.getText()));
        registrosBorrados=renta.setBorrarRenta(renta);
        JOptionPane.showMessageDialog(null, "Registro Borrado\n", 
                    "Información del Sistema", JOptionPane.INFORMATION_MESSAGE);
        int resultadoBitacora=0;
        
        llenadoDeTablas();
        //limpiarTextos();
    }//GEN-LAST:event_Btn_eliminarActionPerformed

    private void Btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_limpiarActionPerformed
        // TODO add your handling code here:
        limpiarTextos();
        habilitarBotones();
    }//GEN-LAST:event_Btn_limpiarActionPerformed

    private void Btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_buscarActionPerformed
    // TODO add your handling code here:
        clsRenta renta = new clsRenta();
        String buscado = Txt_buscado.getText().trim();

        if (buscado.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El campo de búsqueda no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }

        try {
        renta.setId_comprobante(Integer.parseInt(buscado));
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido en el campo de búsqueda.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }

        renta = renta.getBuscarInformacionRentaPorId(renta);

        if (renta != null) {
        // Si la renta es encontrada
        JOptionPane.showMessageDialog(this, "Renta encontrada exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        // Mostrar datos en la interfaz
        Txt_idAlquiler.setText(Integer.toString(renta.getId_comprobante()));
        
        /*SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Txt_fechaInicioRenta.setText(renta.getFecha_alquiler() != null ? sdf.format(renta.getFecha_alquiler()) : "");
        Txt_fechaDevolucionRenta.setText(renta.getFecha_devolucion() != null ? sdf.format(renta.getFecha_devolucion()) : "");*/
        
        // Fechas
        //String fechaInicio = ((JTextField)Txt_fechaInicioRenta.getDateEditor().getUiComponent()).getText();
        //String fechaFin = ((JTextField)Txt_fechaDevolucionRenta.getDateEditor().getUiComponent()).getText();
        if (renta.getFecha_alquiler() != null) {
        Txt_fechaInicioRenta.setDate(renta.getFecha_alquiler());
        }
        if (renta.getFecha_devolucion() != null) {
        Txt_fechaDevolucionRenta.setDate(renta.getFecha_devolucion());
        }
    
        // Estatus Renta
        String estadoActual = renta.getEstatus_alquiler();
        if (estadoActual != null) {
        if (estadoActual.equalsIgnoreCase("Rentado")) {
            Cbo_estatusAlquiler.setSelectedItem("Rentado");
        } else if (estadoActual.equalsIgnoreCase("Devuelto")) {
            Cbo_estatusAlquiler.setSelectedItem("Devuelto");
        } else {
            // Si el estado no coincide con ninguno de los valores esperados
            JOptionPane.showMessageDialog(this, "Estado de alquiler no válido", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }

        // Seleccionar video en Cbo_idVideo
        int CodVideo = renta.getId_video();
        boolean videoEncontrado = false;
        for (int i = 0; i < Cbo_idVideo.getItemCount(); i++) {
        String item = Cbo_idVideo.getItemAt(i).toString().trim();
        try {
            int itemIdV = Integer.parseInt(item.split(" - ")[0]); // Ajusta según el formato de los ítems
            if (itemIdV == CodVideo) {
                Cbo_idVideo.setSelectedIndex(i);
                videoEncontrado = true;
                break;
            }
        } catch (NumberFormatException e) {
            // Ignorar ítems que no se pueden convertir a entero
        }
        }
        if (!videoEncontrado) {
        JOptionPane.showMessageDialog(this, "Video no encontrado en la lista", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

        // Seleccionar cliente en Cbo_cliente
        int CodCliente = renta.getId_cliente();
        boolean clienteEncontrado = false;
        for (int i = 0; i < Cbo_cliente.getItemCount(); i++) {
        String item = Cbo_cliente.getItemAt(i).toString().trim();
        try {
            int itemId = Integer.parseInt(item.split(" - ")[0]); // Ajusta según el formato de los ítems
            if (itemId == CodCliente) {
                Cbo_cliente.setSelectedIndex(i);
                clienteEncontrado = true;
                break;
            }
        } catch (NumberFormatException e) {
            // Ignorar ítems que no se pueden convertir a entero
        }
        }
        if (!clienteEncontrado) {
        JOptionPane.showMessageDialog(this, "Cliente no encontrado en la lista", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        } else {
        // Si la renta no es encontrada
        JOptionPane.showMessageDialog(this, "Renta no encontrada", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Btn_buscarActionPerformed

    private void Btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_actualizarActionPerformed
        // TODO add your handling code here:
        llenadoDeTablas();
    }//GEN-LAST:event_Btn_actualizarActionPerformed

    private void Cbo_estatusAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cbo_estatusAlquilerActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Cbo_estatusAlquilerActionPerformed

    private void Txt_idAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_idAlquilerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_idAlquilerActionPerformed
    

        public void limpiarTextos()
    {
        Txt_idAlquiler.setText("");
        Cbo_cliente.setSelectedIndex(0);
        Cbo_idVideo.setSelectedIndex(0);
        Cbo_estatusAlquiler.setSelectedIndex(0);
        ((JTextField) Txt_fechaInicioRenta.getDateEditor().getUiComponent()).setText("");
        ((JTextField) Txt_fechaDevolucionRenta.getDateEditor().getUiComponent()).setText("");   
        Txt_buscado.setText("");
    }
    public void habilitarBotones()
    {
        Btn_registrar.setEnabled(true);
        Btn_modificar.setEnabled(true);
        Btn_eliminar.setEnabled(true);
    }
    public void desHabilitarBotones()
    {
        Btn_registrar.setEnabled(true);
        Btn_modificar.setEnabled(true);
        Btn_eliminar.setEnabled(true);
    }    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jDialog_Renta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jDialog_Renta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jDialog_Renta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jDialog_Renta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jDialog_Renta dialog = new jDialog_Renta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_actualizar;
    private javax.swing.JButton Btn_ayuda;
    private javax.swing.JButton Btn_buscar;
    private javax.swing.JButton Btn_eliminar;
    private javax.swing.JButton Btn_limpiar;
    private javax.swing.JButton Btn_modificar;
    private javax.swing.JButton Btn_registrar;
    private javax.swing.JComboBox<String> Cbo_cliente;
    private javax.swing.JComboBox<String> Cbo_estatusAlquiler;
    private javax.swing.JComboBox<String> Cbo_idVideo;
    private javax.swing.JTable Tbl_alquilerVideos;
    private javax.swing.JTextField Txt_buscado;
    private com.toedter.calendar.JDateChooser Txt_fechaDevolucionRenta;
    private com.toedter.calendar.JDateChooser Txt_fechaInicioRenta;
    private javax.swing.JTextField Txt_idAlquiler;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_Cliente1;
    private javax.swing.JLabel lbl_Cliente2;
    private javax.swing.JLabel lbl_FechaFin;
    private javax.swing.JLabel lbl_FechaInicio;
    private javax.swing.JLabel lbl_PrecioRenta;
    private javax.swing.JLabel lbl_cantidad4;
    private javax.swing.JLabel lbl_video;
    private javax.swing.JPanel pan_video;
    // End of variables declaration//GEN-END:variables
}
